#!/bin/sh

read -rp 'Password: ' password

salt="$(openssl rand -base64 3)"
sha1=$(
	printf "$password$salt" |
		openssl dgst -binary -sha1 |
		xxd -ps |
		sed "s#\$#$(echo -n $salt | xxd -ps)#" |
		xxd -r -ps |
		base64
)

printf "{SSHA}$sha1\n"
