#!/bin/bash -e

SRC=/usr/share/pacman/override

_diff() {
	if command -v git >/dev/null; then
		git --no-pager diff --no-index --color=always "$@"
	else
		diff -u "$@"
	fi
}

if [ ! -e "$2" ]; then
	touch "$2"
fi

_diff "$2" "$SRC/$1" || :

cat "$SRC/$1" >"$2"
