# Autolaunch sway:
if command -v sway >/dev/null \
	&& [ -z "$WAYLAND_DISPLAY" ] \
	&& [ "$(tty)" = "/dev/tty1" ] && \
	[ "$UID" != 0 ]; then

	if systemctl --user -q is-active sway-session.target; then
		systemctl --user -q stop sway-session.target
	fi
	exec systemd-cat -t sway sway
fi

# Shorthand for copying to clipboard:
alias wcp='wl-copy -p'
