#!/bin/sh

exec kitty \
	--class KittyMenu \
	-o remember_window_size=no \
	-o initial_window_width=40c \
	-o initial_window_height=11c \
	-e /bin/bash -lc '
		compgen -c |
			sort -u |
			fzy |
			xargs -r swaymsg -t command exec -- systemd-run --user
	'
