local Color, c, Group, g, s = require("colorbuddy").setup()
local no = s.NONE

Color.new('fg_1',      '#24292e')
Color.new('fg_2',      '#6a737d')
Color.new('fg_3',      '#babbbc')
Color.new('bg_1',      '#ffffff')
Color.new('bg_2',      '#fafbfc')
Color.new('bg_3',      '#e1e4e8')
Color.new('blue_0',    '#05264c')
Color.new('blue_1',    '#032f62')
Color.new('blue_2',    '#005cc5')
Color.new('blue_3',    '#c8e1ff')
Color.new('blue_4',    '#f1f8ff')
Color.new('red_1',     '#d73a49')
Color.new('red_2',     '#fdb8c0')
Color.new('red_3',     '#ffeef0')
Color.new('green_1',   '#22863a')
Color.new('green_2',   '#acf2bd')
Color.new('green_3',   '#e6ffed')
Color.new('orange_1',  '#e36209')
Color.new('orange_2',  '#fab484')
Color.new('purple_1',  '#6f42c1')
Color.new('yellow_3',  '#fffbdd')

-- Vim Primary Colors

Color.new('Red', "#e88388")
Color.new('DarkRed', "#e06c75")
Color.new('Blue', "#61afef")
Color.new('DarkBlue', "#528bff")
Color.new('Green', "#98c379")
Color.new('DarkGreen', "#50a14f")
Color.new('Orange', "#d19a66")
Color.new('DarkOrange', "#c18401")
Color.new('Yellow', "#e5c07b")
Color.new('DarkYellow', "#986801")
Color.new('Purple', "#a626a4")
Color.new('Violet', '#b294bb')
Color.new('Magenta', '#ff80ff')
Color.new('DarkMagenta', '#a626a4')
Color.new('Black', "#333841")
Color.new('Grey', "#636d83")
Color.new('White',  '#f2e5bc')
Color.new('Cyan', '#8abeb7')
Color.new('DarkCyan', '#80a0ff')
Color.new('Aqua', '#8ec07c')
Color.new('pink', "#d291e4")

-- Vim Terminal

vim.g.terminal_color_0  = c.bg_2:to_rgb()
vim.g.terminal_color_8  = c.bg_3:to_rgb()
vim.g.terminal_color_1  = c.red_1:to_rgb()
vim.g.terminal_color_9  = c.red_1:to_rgb()
vim.g.terminal_color_2  = c.green_1:to_rgb()
vim.g.terminal_color_10 = c.green_1:to_rgb()
vim.g.terminal_color_3  = c.orange_1:to_rgb()
vim.g.terminal_color_11 = c.orange_1:to_rgb()
vim.g.terminal_color_4  = c.blue_2:to_rgb()
vim.g.terminal_color_12 = c.blue_2:to_rgb()
vim.g.terminal_color_5  = c.purple_1:to_rgb()
vim.g.terminal_color_13 = c.purple_1:to_rgb()
vim.g.terminal_color_6  = "#65c2cd"
vim.g.terminal_color_14 = "#65c2cd"
vim.g.terminal_color_7  = c.fg_2:to_rgb()
vim.g.terminal_color_15 = c.fg_1:to_rgb()

-- Editor

Group.new('Normal',        c.fg_1,    c.bg_1,      no)
Group.new('bold',          c.none,    c.none,      s.bold)
Group.new('ColorColumn',   c.none,    c.bg_2,      no)
Group.new('Conceal',       c.fg_3,    c.bg_1,      no)
Group.new('Cursor',        c.none,    c.fg_1,      no)
Group.new('CursorIM',      c.none,    c.none,      no)
Group.new('CursorColumn',  c.none,    c.bg_2,      no)
Group.new('CursorLine',    c.none,    c.bg_2,      no)
Group.new('Directory',     c.blue_2,  c.none,      no)
Group.new('ErrorMsg',      c.red_1,   c.none,      no)
Group.new('VertSplit',     c.fg_3,    c.none,      no)
Group.new('Folded',        c.fg_3,    c.none,      no)
Group.new('FoldColumn',    c.fg_3,    c.none,      no)
Group.new('IncSearch',     c.none,    c.orange_2,  no)
Group.new('LineNr',        c.fg_3,    c.none,      no)
Group.new('CursorLineNr',  c.none,    c.bg_2,      no)
Group.new('MatchParen',    c.none,    c.yellow_3,  no)
Group.new('Italic',        c.none,    c.none,      s.italic)
Group.new('ModeMsg',       c.fg_1,    c.none,      no)
Group.new('MoreMsg',       c.fg_1,    c.none,      no)
Group.new('NonText',       c.fg_3,    c.none,      no)
Group.new('PMenu',         c.none,    c.bg_2,      no)
Group.new('PMenuSel',      c.none,    c.blue_3,    no)
Group.new('PMenuSbar',     c.none,    c.bg_3,      no)
Group.new('PMenuThumb',    c.none,    c.fg_3,      no)
Group.new('Question',      c.blue_2,  c.none,      no)
Group.new('Search',        c.none,    c.yellow_3,  no)
Group.new('SpecialKey',    c.fg_2,    c.none,      no)
Group.new('Whitespace',    c.fg_2,    c.none,      no)
Group.new('StatusLine',    c.blue_0,  c.blue_4,    no)
Group.new('StatusLineNC',  c.fg_2,    c.bg_2,      no)
Group.new('TabLine',       c.none,    c.blue_4,    no)
Group.new('TabLineFill',   c.none,    c.none,      no)
Group.new('TabLineSel',    c.none,    c.blue_3,    no)
Group.new('Title',         c.fg_1,    c.none,      s.bold)
Group.new('Visual',        c.none,    c.yellow_3,  no)
Group.new('VisualNOS',     c.none,    c.yellow_3,  no)
Group.new('WarningMsg',    c.red_1,   c.none,      no)
Group.new('TooLong',       c.red_1,   c.none,      no)
Group.new('WildMenu',      c.fg_1,    c.blue_3,    no)
Group.new('SignColumn',    c.none,    c.none,      no)

-- Standard Syntax

Group.new('Comment',         c.fg_2,      c.none,   s.italic)
Group.new('Constant',        c.orange_1,  c.none,   no)
Group.new('String',          c.blue_1,    c.none,   no)
Group.new('Character',       g.String,    c.none,   no)
Group.new('Number',          c.blue_2,    c.none,   no)
Group.new('Boolean',         c.blue_2,    c.none,   no)
Group.new('Float',           c.blue_2,    c.none,   no)
Group.new('Identifier',      c.red_1,     c.none,   no)
Group.new('Function',        c.purple_1,  c.none,   no)
Group.new('Statement',       c.red_1,     c.none,   no)
Group.new('Conditional',     c.red_1,     c.none,   no)
Group.new('Repeat',          c.red_1,     c.none,   no)
Group.new('Label',           c.purple_1,  c.none,   no)
Group.new('Operator',        c.blue_2,    c.none,   no)
Group.new('Keyword',         c.red_1,     c.none,   no)
Group.new('Exception',       c.red_1,     c.none,   no)
Group.new('PreProc',         c.red_1,     c.none,   no)
Group.new('Include',         c.red_1,     c.none,   no)
Group.new('Define',          c.purple_1,  c.none,   no)
Group.new('Macro',           c.purple_1,  c.none,   no)
Group.new('PreCondit',       c.red_1,     c.none,   no)
Group.new('Type',            c.blue_2,    c.none,   no)
Group.new('StorageClass',    c.red_1,     c.none,   no)
Group.new('Structure',       c.orange_1,  c.none,   no)
Group.new('Typedef',         c.red_1,     c.none,   no)
Group.new('Special',         c.blue_2,    c.none,   no)
Group.new('SpecialChar',     c.blue_2,    c.none,   no)
Group.new('Tag',             c.none,      c.none,   no)
Group.new('Delimiter',       c.blue_2,    c.none,   no)
Group.new('SpecialComment',  c.green_1,   c.none,   no)
Group.new('Debug',           c.none,      c.none,   no)
Group.new('Underlined',      c.none,      c.none,   s.underline)
Group.new('Ignore',          c.none,      c.none,   no)
Group.new('Error',           c.none,      c.red_3,  s.bold)
Group.new('Todo',            c.red_1,     c.none,   s.bold)

-- Diff

Group.new('DiffAdd',     c.none,  c.green_3,   no)
Group.new('DiffChange',  c.none,  c.yellow_3,  no)
Group.new('DiffDelete',  c.none,  c.red_3,     no)
Group.new('DiffText',    c.none,  c.yellow_3,  s.undercurl)

Group.new('DiffAdded',    c.none,     g.DiffAdd,     no)
Group.new('DiffRemoved',  c.none,     g.DiffDelete,  no)
Group.new('DiffFile',     c.green_1,  c.none,        no)
Group.new('DiffNewFile',  c.red_1,    c.none,        no)
Group.new('DiffLine',     c.blue_2,   c.none,        no)

-- TreeSitter

Group.new('TSAnnotation',          c.blue_2,       c.none,   no)
Group.new('TSAttribute',           c.blue_2,       c.none,   no)
Group.new('TSBoolean',             g.Boolean,      c.none,   no)
Group.new('TSCharacter',           g.String,       c.none,   no)
Group.new('TSConditional',         g.Conditional,  c.none,   no)
Group.new('TSConstant',            g.Constant,     c.none,   no)
Group.new('TSConstBuiltin',        c.blue_2,       c.none,   no)
Group.new('TSConstMacro',          c.blue_2,       c.none,   no)
Group.new('TSConstructor',         g.Function,     c.none,   no)
Group.new('TSEmphasis',            c.none,         c.none,   s.italic)
Group.new('TSError',               c.none,         g.Error,  no)
Group.new('TSException',           g.Exception,    c.none,   no)
Group.new('TSField',               c.none,         c.none,   no)
Group.new('TSFloat',               g.Float,        c.none,   no)
Group.new('TSFunction',            g.Function,     c.none,   no)
Group.new('TSFuncBuiltin',         g.Function,     c.none,   no)
Group.new('TSFuncMacro',           c.blue_2,       c.none,   no)
Group.new('TSInclude',             g.Include,      c.none,   no)
Group.new('TSKeyword',             c.red_1,        c.none,   no)
Group.new('TSKeywordFunction',     c.red_1,        c.none,   no)
Group.new('TSKeywordOperator',     g.Operator,     c.none,   no)
Group.new('TSLabel',               c.blue_2,       c.none,   no)
Group.new('TSLiteral',             c.orange_1,     c.none,   no)
Group.new('TSMethod',              g.Function,     c.none,   no)
Group.new('TSNamespace',           c.red_1,        c.none,   no)
Group.new('TSNumber',              g.Number,       c.none,   no)
Group.new('TSOperator',            c.none,         c.none,   no)
Group.new('TSParameter',           c.none,         c.none,   no)
Group.new('TSParameterReference',  c.none,         c.none,   no)
Group.new('TSProperty',            c.none,         c.none,   no)
Group.new('TSPunctBracket',        c.none,         c.none,   no)
Group.new('TSPunctDelimiter',      c.none,         c.none,   no)
Group.new('TSPunctSpecial',        c.none,         c.none,   no)
Group.new('TSRepeat',              g.Repeat,       c.none,   no)
Group.new('TSString',              g.String,       c.none,   no)
Group.new('TSStringEscape',        c.blue_2,       c.none,   no)
Group.new('TSStringRegex',         g.String,       c.none,   no)
Group.new('TSStrong',              c.none,         c.none,   s.bold)
Group.new('TSStructure',           g.Structure,    c.none,   no)
Group.new('TSTag',                 c.green_1,      c.none,   no)
Group.new('TSTagDelimiter',        c.none,         c.none,   no)
Group.new('TSText',                c.none,         c.none,   no)
Group.new('TSTitle',               c.blue_2,       c.none,   s.bold)
Group.new('TSType',                c.orange_1,     c.none,   no)
Group.new('TSTypeBuiltin',         c.orange_1,     c.none,   no)
Group.new('TSUnderline',           c.none,         c.none,   s.underline)
Group.new('TSURI',                 c.blue_2,       c.none,   no)
Group.new('TSVariable',            c.none,         c.none,   no)
Group.new('TSVariableBuiltin',     c.none,         c.none,   no)
